using System;
using System.Diagnostics;
using System.IO;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace Muco.Editor
{
    /// <summary>
    /// Pre-build hook that reads the MUCO package version from package.json and the
    /// current git commit, then writes Runtime/Generated/MucoPackageInfo.cs so the
    /// runtime code always has up-to-date values without hard-coding.
    ///
    /// During a build (e.g. cloud CI that does not clone .git) set the environment
    /// variable MUCO_PACKAGE_COMMIT to the desired commit hash.
    /// </summary>
    public class MucoPackageInfoGenerator : IPreprocessBuildWithReport
    {
        // Run early -- most pre-process callbacks run before this.
        public int callbackOrder => -100;

        public void OnPreprocessBuild(BuildReport report)
        {
            // Locate the package root by walking up from this script's asset path.
            // AssetDatabase works because this runs in the editor during a build.
            var guids = AssetDatabase.FindAssets("t:Script MucoPackageInfoGenerator");
            if (guids.Length == 0)
            {
                UnityEngine.Debug.LogWarning(
                    "[MucoPackageInfoGenerator] Could not locate generator script in AssetDatabase."
                );
                return;
            }

            string scriptPath = AssetDatabase.GUIDToAssetPath(guids[0]);
            // scriptPath is like "Packages/com.phenomenalviborg.muco/Editor/MucoPackageInfoGenerator.cs"
            string packageRoot = Directory.GetParent(scriptPath)!.Parent!.FullName;

            string packageJsonPath = Path.Combine(packageRoot, "package.json");
            if (!File.Exists(packageJsonPath))
            {
                UnityEngine.Debug.LogWarning(
                    $"[MucoPackageInfoGenerator] package.json not found at {packageJsonPath}"
                );
                return;
            }

            // --- Read version from package.json ----------------------------------
            string json = File.ReadAllText(packageJsonPath);
            // Brute-force parse: find "version": "..." in the JSON.
            // A proper JSON parser would be better, but this avoids adding a dependency.
            string version = "unknown";
            const string versionKey = "\"version\": \"";
            int idx = json.IndexOf(versionKey, StringComparison.Ordinal);
            if (idx >= 0)
            {
                int start = idx + versionKey.Length;
                int end   = json.IndexOf("\"", start, StringComparison.Ordinal);
                if (end > start)
                    version = json.Substring(start, end - start);
            }

            // --- Read git commit ------------------------------------------------
            string commit = Environment.GetEnvironmentVariable("MUCO_PACKAGE_COMMIT");
            if (string.IsNullOrEmpty(commit))
            {
                try
                {
                    var psi = new ProcessStartInfo("git", "rev-parse --short HEAD")
                    {
                        CreateNoWindow = true,
                        RedirectStandardOutput = true,
                        UseShellExecute = false,
                        WorkingDirectory = packageRoot,
                    };
                    using var proc = Process.Start(psi);
                    if (proc != null)
                    {
                        string line = proc.StandardOutput.ReadToEnd()?.Trim();
                        proc.WaitForExit(3000);
                        if (proc.ExitCode == 0 && !string.IsNullOrEmpty(line))
                            commit = line;
                    }
                }
                catch
                {
                    commit = "unknown";
                }
            }

            if (string.IsNullOrEmpty(commit))
                commit = "unknown";

            // --- Write the generated file --------------------------------------
            string generatedDir = Path.Combine(packageRoot, "Runtime", "Network");
            Directory.CreateDirectory(generatedDir);
            string outputPath = Path.Combine(generatedDir, "MucoPackageInfo.cs");

            string content =
                "// <auto-generated />\n" +
                "// This file is automatically generated before each build by\n" +
                "// MucoPackageInfoGenerator. Edit the generator, not this file.\n" +
                "\n" +
                "namespace Muco\n" +
                "{\n" +
                "    public static class MucoPackageInfo\n" +
                "    {\n" +
                "        public const string Version = \"" + version + "\";\n" +
                "        public const string Commit  = \"" + commit + "\";\n" +
                "    }\n" +
                "}\n";
            File.WriteAllText(outputPath, content);
            AssetDatabase.Refresh();

            // --- Update package.json description --------------------------------
            const string descriptionKey = "\"description\": \"";
            int descIdx = json.IndexOf(descriptionKey, StringComparison.Ordinal);
            if (descIdx >= 0)
            {
                int descStart = descIdx + descriptionKey.Length;
                int descEnd   = json.IndexOf("\"", descStart, StringComparison.Ordinal);
                if (descEnd > descStart)
                {
                    string newDesc = "MUCO Core Package v" + version + " (commit " + commit + ")";
                    string oldDesc = json.Substring(descStart, descEnd - descStart);
                    if (oldDesc != newDesc)
                    {
                        string updatedJson = json.Substring(0, descStart) + newDesc + json.Substring(descEnd);
                        File.WriteAllText(packageJsonPath, updatedJson);
                        AssetDatabase.Refresh();
                    }
                }
            }

            UnityEngine.Debug.Log(
                "[MucoPackageInfoGenerator] Generated " + outputPath + ": Version=" + version + ", Commit=" + commit
            );
        }
    }
}